// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CiPlotAnnotationX wrapper class

class CiPlotAnnotationX : public COleDispatchDriver
{
public:
	CiPlotAnnotationX() {}		// Calls COleDispatchDriver default constructor
	CiPlotAnnotationX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotAnnotationX(const CiPlotAnnotationX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetReference();
	void SetReference(long nNewValue);
	double GetX();
	void SetX(double newValue);
	double GetY();
	void SetY(double newValue);
	double GetX2();
	void SetX2(double newValue);
	double GetY2();
	void SetY2(double newValue);
	double GetWidth();
	void SetWidth(double newValue);
	double GetHeight();
	void SetHeight(double newValue);
	unsigned long GetPenColor();
	void SetPenColor(unsigned long newValue);
	long GetPenStyle();
	void SetPenStyle(long nNewValue);
	long GetPenWidth();
	void SetPenWidth(long nNewValue);
	unsigned long GetBrushColor();
	void SetBrushColor(unsigned long newValue);
	long GetBrushStyle();
	void SetBrushStyle(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	CString GetChannelName();
	void SetChannelName(LPCTSTR lpszNewValue);
	unsigned long GetFontColor();
	void SetFontColor(unsigned long newValue);
	long GetTextRotation();
	void SetTextRotation(long nNewValue);
};
