// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CiPlotToolBarX wrapper class

class CiPlotToolBarX : public COleDispatchDriver
{
public:
	CiPlotToolBarX() {}		// Calls COleDispatchDriver default constructor
	CiPlotToolBarX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotToolBarX(const CiPlotToolBarX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	double GetStartPercent();
	void SetStartPercent(double newValue);
	double GetStopPercent();
	void SetStopPercent(double newValue);
	BOOL GetShowCopyButton();
	void SetShowCopyButton(BOOL bNewValue);
	BOOL GetShowSaveButton();
	void SetShowSaveButton(BOOL bNewValue);
	BOOL GetShowPrintButton();
	void SetShowPrintButton(BOOL bNewValue);
	BOOL GetShowEditButton();
	void SetShowEditButton(BOOL bNewValue);
	long GetZOrder();
	void SetZOrder(long nNewValue);
	BOOL GetHorizontal();
	void SetHorizontal(BOOL bNewValue);
	BOOL GetShowResumeButton();
	void SetShowResumeButton(BOOL bNewValue);
	BOOL GetShowPauseButton();
	void SetShowPauseButton(BOOL bNewValue);
	BOOL GetShowAxesModeButtons();
	void SetShowAxesModeButtons(BOOL bNewValue);
	BOOL GetShowZoomInOutButtons();
	void SetShowZoomInOutButtons(BOOL bNewValue);
	BOOL GetShowZoomBoxButton();
	void SetShowZoomBoxButton(BOOL bNewValue);
	BOOL GetShowCursorButton();
	void SetShowCursorButton(BOOL bNewValue);
	void TurnOffCursor();
	BOOL GetZoomBoxActive();
	BOOL GetCursorActive();
	void DoButtonClickResume();
	void DoButtonClickPause();
	void DoButtonClickScrollAxesMode();
	void DoButtonClickZoomAxesMode();
	void DoButtonClickZoomBox();
	void DoButtonClickZoomOut();
	void DoButtonClickZoomIn();
	void DoButtonClickCursor();
	void DoButtonClickEdit();
	void DoButtonClickCopy();
	void DoButtonClickSave();
	void DoButtonClickPrint();
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetPopupEnabled();
	void SetPopupEnabled(BOOL bNewValue);
	double GetZoomInOutFactor();
	void SetZoomInOutFactor(double newValue);
	long GetWidth();
	long GetHeight();
};
