// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CiPlotLegendX wrapper class

class CiPlotLegendX : public COleDispatchDriver
{
public:
	CiPlotLegendX() {}		// Calls COleDispatchDriver default constructor
	CiPlotLegendX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotLegendX(const CiPlotLegendX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	double GetStartPercent();
	void SetStartPercent(double newValue);
	double GetStopPercent();
	void SetStopPercent(double newValue);
	double GetMarginLeft();
	void SetMarginLeft(double newValue);
	double GetMarginTop();
	void SetMarginTop(double newValue);
	double GetMarginRight();
	void SetMarginRight(double newValue);
	double GetMarginBottom();
	void SetMarginBottom(double newValue);
	unsigned long GetBackGroundColor();
	void SetBackGroundColor(unsigned long newValue);
	BOOL GetBackGroundTransparent();
	void SetBackGroundTransparent(BOOL bNewValue);
	unsigned long GetSelectedItemBackGroundColor();
	void SetSelectedItemBackGroundColor(unsigned long newValue);
	COleFont GetSelectedItemFont();
	void SetSelectedItemFont(LPDISPATCH newValue);
	BOOL GetShowColumnXAxisTitle();
	void SetShowColumnXAxisTitle(BOOL bNewValue);
	BOOL GetShowColumnYAxisTitle();
	void SetShowColumnYAxisTitle(BOOL bNewValue);
	BOOL GetShowColumnMarker();
	void SetShowColumnMarker(BOOL bNewValue);
	BOOL GetShowColumnXValue();
	void SetShowColumnXValue(BOOL bNewValue);
	BOOL GetShowColumnYValue();
	void SetShowColumnYValue(BOOL bNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	double GetColumnSpacing();
	void SetColumnSpacing(double newValue);
	double GetRowSpacing();
	void SetRowSpacing(double newValue);
	BOOL GetHorizontal();
	void SetHorizontal(BOOL bNewValue);
	long GetZOrder();
	void SetZOrder(long nNewValue);
	unsigned long GetFontColor();
	void SetFontColor(unsigned long newValue);
	unsigned long GetSelectedItemFontColor();
	void SetSelectedItemFontColor(unsigned long newValue);
	BOOL GetShowColumnLine();
	void SetShowColumnLine(BOOL bNewValue);
	BOOL GetColumnTitlesVisible();
	void SetColumnTitlesVisible(BOOL bNewValue);
	COleFont GetColumnTitlesFont();
	void SetColumnTitlesFont(LPDISPATCH newValue);
	unsigned long GetColumnTitlesFontColor();
	void SetColumnTitlesFontColor(unsigned long newValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetPopupEnabled();
	void SetPopupEnabled(BOOL bNewValue);
	long GetWidth();
	long GetHeight();
};
