// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CiPlotDataViewX wrapper class

class CiPlotDataViewX : public COleDispatchDriver
{
public:
	CiPlotDataViewX() {}		// Calls COleDispatchDriver default constructor
	CiPlotDataViewX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotDataViewX(const CiPlotDataViewX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	double GetStartPercent();
	void SetStartPercent(double newValue);
	double GetStopPercent();
	void SetStopPercent(double newValue);
	CString GetTitle();
	void SetTitle(LPCTSTR lpszNewValue);
	CString GetGridXAxisName();
	void SetGridXAxisName(LPCTSTR lpszNewValue);
	CString GetGridYAxisName();
	void SetGridYAxisName(LPCTSTR lpszNewValue);
	BOOL GetGridShow();
	void SetGridShow(BOOL bNewValue);
	unsigned long GetGridLineColor();
	void SetGridLineColor(unsigned long newValue);
	BOOL GetGridLineShowLeft();
	void SetGridLineShowLeft(BOOL bNewValue);
	BOOL GetGridLineShowRight();
	void SetGridLineShowRight(BOOL bNewValue);
	BOOL GetGridLineShowTop();
	void SetGridLineShowTop(BOOL bNewValue);
	BOOL GetGridLineShowBottom();
	void SetGridLineShowBottom(BOOL bNewValue);
	BOOL GetGridLineShowXMajors();
	void SetGridLineShowXMajors(BOOL bNewValue);
	BOOL GetGridLineShowXMinors();
	void SetGridLineShowXMinors(BOOL bNewValue);
	BOOL GetGridLineShowYMajors();
	void SetGridLineShowYMajors(BOOL bNewValue);
	BOOL GetGridLineShowYMinors();
	void SetGridLineShowYMinors(BOOL bNewValue);
	long GetGridLineMajorStyle();
	void SetGridLineMajorStyle(long nNewValue);
	long GetGridLineMinorStyle();
	void SetGridLineMinorStyle(long nNewValue);
	BOOL GetBackGroundTransparent();
	void SetBackGroundTransparent(BOOL bNewValue);
	unsigned long GetBackGroundColor();
	void SetBackGroundColor(unsigned long newValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetPopupEnabled();
	void SetPopupEnabled(BOOL bNewValue);
	long GetWidth();
	long GetHeight();
};
