// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CiPlotAxisX;
class CiPlotLegendX;
class CiPlotToolBarX;
class CiPlotDataViewX;
class CiPlotLabelX;
class COleFont;
class CiPlotAnnotationX;
class CPicture;
class CiPlotDataCursorX;
class CiPlotLimitX;
class CiPlotChannelX;

/////////////////////////////////////////////////////////////////////////////
// CiPlotX wrapper class

class CiPlotX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CiPlotX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1791c036, 0x8981, 0x492a, { 0xbd, 0x28, 0xf2, 0x33, 0x1b, 0xc9, 0xb7, 0xc7 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

	BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
	pPersist, bStorage, bstrLicKey); }

	// Operations
public:
	long GetDataViewZHorz();
	void SetDataViewZHorz(long newValue);
	long GetDataViewZVert();
	void SetDataViewZVert(long newValue);
	BOOL GetXYAxesReverse();
	void SetXYAxesReverse(BOOL newValue);
	long GetOuterMarginLeft();
	void SetOuterMarginLeft(long newValue);
	long GetOuterMarginTop();
	void SetOuterMarginTop(long newValue);
	long GetOuterMarginRight();
	void SetOuterMarginRight(long newValue);
	long GetOuterMarginBottom();
	void SetOuterMarginBottom(long newValue);
	long GetPrintOrientation();
	void SetPrintOrientation(long newValue);
	double GetPrintMarginLeft();
	void SetPrintMarginLeft(double newValue);
	double GetPrintMarginTop();
	void SetPrintMarginTop(double newValue);
	double GetPrintMarginRight();
	void SetPrintMarginRight(double newValue);
	double GetPrintMarginBottom();
	void SetPrintMarginBottom(double newValue);
	BOOL GetPrintShowDialog();
	void SetPrintShowDialog(BOOL newValue);
	long GetUpdateFrameRate();
	void SetUpdateFrameRate(long newValue);
	unsigned long GetBackGroundColor();
	void SetBackGroundColor(unsigned long newValue);
	long GetBorderStyle();
	void SetBorderStyle(long newValue);
	BOOL GetAutoFrameRate();
	void SetAutoFrameRate(BOOL newValue);
	void AboutBox();
	CiPlotAxisX GetXAxis(long Index);
	CiPlotAxisX GetYAxis(long Index);
	CiPlotLegendX GetLegend(long Index);
	CiPlotToolBarX GetToolBar(long Index);
	CiPlotDataViewX GetDataView(long Index);
	void DisableLayoutManager();
	void EnableLayoutManager();
	void DisableAllTracking();
	void EnableAllTracking();
	long AddXAxis();
	long AddYAxis();
	long AddLegend();
	long AddToolBar();
	long AddDataView();
	long AddChannel();
	void RemoveAllXAxes();
	void RemoveAllYAxes();
	void RemoveAllLegends();
	void RemoveAllToolBars();
	void RemoveAllDataViews();
	void RemoveAllChannels();
	long GetXAxisCount();
	long GetYAxisCount();
	long GetLegendCount();
	long GetToolBarCount();
	long GetDataViewCount();
	long GetChannelCount();
	BOOL GetHintsShow();
	void SetHintsShow(BOOL newValue);
	long GetHintsPause();
	void SetHintsPause(long newValue);
	long GetHintsHidePause();
	void SetHintsHidePause(long newValue);
	void DeleteToolBar(long Index);
	void DeleteLegend(long Index);
	void DeleteXAxis(long Index);
	void DeleteYAxis(long Index);
	void DeleteChannel(long Index);
	void DeleteDataView(long Index);
	void ShowPropertyEditor();
	BOOL GetTitleVisible();
	void SetTitleVisible(BOOL newValue);
	CString GetTitleText();
	void SetTitleText(LPCTSTR newValue);
	double GetTitleMargin();
	void SetTitleMargin(double newValue);
	COleFont GetTitleFont();
	void SetTitleFont(LPDISPATCH newValue);
	unsigned long GetTitleFontColor();
	void SetTitleFontColor(unsigned long newValue);
	void RemoveAllAnnotations();
	void DeleteAnnotation(long Index);
	long AddAnnotation();
	long GetAnnotationCount();
	CiPlotAnnotationX GetAnnotation(long Index);
	long GetChannelIndexByName(LPCTSTR Value);
	long GetXAxisIndexByName(LPCTSTR Value);
	long GetYAxisIndexByName(LPCTSTR Value);
	BOOL GetUserCanEditObjects();
	void SetUserCanEditObjects(BOOL newValue);
	void PrintChart();
	void CopyToClipBoard();
	void Save();
	CPicture GetSnapShotPicture();
	void RepaintAll();
	void BeginUpdate();
	void EndUpdate();
	void Lock();
	void Unlock();
	void ClearAllData();
	void AddDataArray(double XValue, VARIANT Data);
	double GetNow();
	void SavePropertiesToFile(LPCTSTR FileName);
	void LoadPropertiesFromFile(LPCTSTR FileName);
	void SaveDataToFile(LPCTSTR FileName);
	void LoadDataFromFile(LPCTSTR FileName);
	CString GetLogFileName();
	void SetLogFileName(LPCTSTR newValue);
	long GetLogBufferSize();
	void SetLogBufferSize(long newValue);
	void LogActivate(BOOL Append);
	void LogDeactivate();
	BOOL GetLoggingActive();
	long GetComponentHandle();
	CiPlotDataCursorX GetDataCursor(long Index);
	long GetDataCursorCount();
	long AddDataCursor();
	void DeleteDataCursor(long Index);
	void RemoveAllDataCursors();
	CiPlotLimitX GetLimit(long Index);
	long GetLimitCount();
	long AddLimit();
	void DeleteLimit(long Index);
	void RemoveAllLimits();
	void SaveImageToBitmap(LPCTSTR FileName);
	void SaveImageToMetaFile(LPCTSTR FileName);
	void SaveImageToJPEG(LPCTSTR FileName, long Compression, BOOL Progressive);
	void SaveTranslationsToFile(LPCTSTR FileName);
	void LoadTranslationsFromFile(LPCTSTR FileName);
	void RemoveAllTranslations();
	void DeleteTranslation(long Index);
	long AddTranslation(LPCTSTR OriginalString, LPCTSTR ReplacementString);
	long TranslationCount();
	CString GetTranslationOriginalString(long Index);
	CString GetTranslationReplacementString(long Index);
	CiPlotLabelX GetLabels(long Index);
	long GetLabelCount();
	long AddLabel();
	void DeleteLabel(long Index);
	void RemoveAllLabels();
	VARIANT GetBytesJPEG(long Compression, BOOL Progressive);
	long GetObjectPointer();
	BOOL GetOptionSaveAllProperties();
	void SetOptionSaveAllProperties(BOOL newValue);
	COleFont GetHintsFont();
	void SetHintsFont(COleFont newValue);
	unsigned long GetHintsFontColor();
	void SetHintsFontColor(unsigned long newValue);
	COleFont GetAnnotationDefaultFont();
	void SetAnnotationDefaultFont(COleFont newValue);
	unsigned long GetAnnotationDefaultFontColor();
	void SetAnnotationDefaultFontColor(unsigned long newValue);
	long GetAnnotationDefaultBrushStlye();
	void SetAnnotationDefaultBrushStlye(long newValue);
	unsigned long GetAnnotationDefaultBrushColor();
	void SetAnnotationDefaultBrushColor(unsigned long newValue);
	long GetAnnotationDefaultPenStlye();
	void SetAnnotationDefaultPenStlye(long newValue);
	unsigned long GetAnnotationDefaultPenColor();
	void SetAnnotationDefaultPenColor(unsigned long newValue);
	long GetAnnotationDefaultPenWidth();
	void SetAnnotationDefaultPenWidth(long newValue);
	long GetWidth();
	void SetWidth(long newValue);
	long GetHeight();
	void SetHeight(long newValue);
	BOOL GetUserCanAddRemoveChannels();
	void SetUserCanAddRemoveChannels(BOOL newValue);
	void SaveAnnotationsToFile(LPCTSTR FileName);
	void LoadAnnotationsFromFile(LPCTSTR FileName);
	void iPaintToDC(long X, long Y, BOOL Transparent, long DC);
	BOOL GetVisible();
	void SetVisible(BOOL newValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL newValue);
	long GetEditorFormStyle();
	void SetEditorFormStyle(long newValue);
	long GetCopyToClipBoardFormat();
	void SetCopyToClipBoardFormat(long newValue);
	CString GetPrintDocumentName();
	void SetPrintDocumentName(LPCTSTR newValue);
	void ImageListClear(long ImageListIndex);
	void ImageListLoadFromResourceID(long ImageListIndex, unsigned long Instance, long ResID);
	void ImageListLoadFromResourceName(long ImageListIndex, unsigned long Instance, LPCTSTR ResName);
	CString GetPrinterName();
	void SetPrinterName(LPCTSTR newValue);
	BOOL GetClipAnnotationsToAxes();
	void SetClipAnnotationsToAxes(BOOL newValue);
	BOOL GetBackGroundGradientEnabled();
	void SetBackGroundGradientEnabled(BOOL newValue);
	long GetBackGroundGradientDirection();
	void SetBackGroundGradientDirection(long newValue);
	unsigned long GetBackGroundGradientStartColor();
	void SetBackGroundGradientStartColor(unsigned long newValue);
	unsigned long GetBackGroundGradientStopColor();
	void SetBackGroundGradientStopColor(unsigned long newValue);
	LPDISPATCH GetTable(long Index);
	long GetTableCount();
	long AddTable();
	void DeleteTable(long Index);
	void RemoveAllTables();
	void ReCalcLayout();
	void TransferChannelData(long SourceChannelIndex, long DestinationChannelIndex, long StartIndex, long StopIndex);
	void ImageListAdd(long ImageListIndex, LPDISPATCH APicture);
	long GetDataFileColumnSeparator();
	void SetDataFileColumnSeparator(long newValue);
	long GetDataFileFormat();
	void SetDataFileFormat(long newValue);
	CString GetLastPropertiesFileName();
	CString GetLastDataFileName();
	long GetDataViewIndexByName(LPCTSTR Value);
	long GetToolBarIndexByName(LPCTSTR Value);
	long GetLegendIndexByName(LPCTSTR Value);
	long GetAnnotationIndexByName(LPCTSTR Value);
	long GetDataCursorIndexByName(LPCTSTR Value);
	long GetLabelIndexByName(LPCTSTR Value);
	long GetLimitIndexByName(LPCTSTR Value);
	long GetTableIndexByName(LPCTSTR Value);
	CiPlotToolBarX GetToolBarByName(LPCTSTR Value);
	CiPlotLegendX GetLegendByName(LPCTSTR Value);
	LPDISPATCH GetTableByName(LPCTSTR Value);
	CiPlotAxisX GetXAxisByName(LPCTSTR Value);
	CiPlotAxisX GetYAxisByName(LPCTSTR Value);
	CiPlotDataViewX GetDataViewByName(LPCTSTR Value);
	CiPlotDataCursorX GetDataCursorByName(LPCTSTR Value);
	CiPlotLimitX GetLimitByName(LPCTSTR Value);
	CiPlotLabelX GetLabelByName(LPCTSTR Value);
	CiPlotAnnotationX GetAnnotationByName(LPCTSTR Value);
	VARIANT GetBytesPNG(long Compression);
	void SaveImageToPNG(LPCTSTR FileName, long Compression);
	CiPlotChannelX GetChannel(long Index);
	CiPlotChannelX GetChannelByName(LPCTSTR Value);

	enum
	{
		iptPlot = 0,
		iptPlotXY = 1
	}TxiPlotType;
	enum
	{
		poPortrait = 0,
		poLandscape = 1
	}TxPrinterOrientation;
	enum
	{
		ibsNone = 0,
		ibsRaised = 1,
		ibsLowered = 2
	}TxiBevelStyle;
	enum
	{
		mbLeft = 0,
		mbRight = 1,
		mbMiddle = 2
	}TxMouseButton;
	enum
	{
		ipsSignificantDigits = 0,
		ipsFixedDecimalPoints = 1
	}TxiPrecisionStyle;
	enum
	{
		iptfValue = 0,
		iptfExponent = 1,
		iptfPrefix = 2,
		iptfDateTime = 3,
		iptfPrice32nds = 4,
		iptfThousands = 5
	}TxiPlotTextFormat;
	enum
	{
		ipstLinear = 0,
		ipstLog10 = 1
	}TxiPlotScaleType;
	enum
	{
		iptsScaleMinMax = 0,
		iptsScaleMax = 1,
		iptsScaleMin = 2,
		iptsScrollSmooth = 3,
		iptsScrollPage = 4,
		iptsExpandCollapse = 5,
		iptsExpandCollapseFast = 6
	}TxiPlotTrackingStyle;
	enum
	{
		ipafsMin = 0,
		ipafsMax = 1,
		ipafsAuto = 2,
		ipafsNone = 3
	}TxiPlotAlignFirstStyle;
	enum
	{
		iplsSolid = 0,
		iplsDash = 1,
		iplsDot = 2,
		iplsDashDot = 3,
		iplsDashDotDot = 4
	}TxiPlotLineStyle;
	enum
	{
		ipmsCircle = 0,
		ipmsSquare = 1,
		ipmsDiamond = 2,
		ipmsCross = 3,
		ipmsPlus = 4,
		ipmsTriangleUp = 5,
		ipmsTriangleDown = 6,
		ipmsTriangleLeft = 7,
		ipmsTriangleRight = 8,
		ipmsVerticalLine = 9,
		ipmsHorizontalLine = 10,
		ipmsCharacter = 11
	}TxiPlotMarkerStyle;
	enum
	{
		psSolid = 0,
		psDash = 1,
		psDot = 2,
		psDashDot = 3,
		psDashDotDot = 4,
		psClear = 5,
		psInsideFrame = 6
	}TxPenStyle;
	enum
	{
		bsSolid = 0,
		bsClear = 1,
		bsHorizontal = 2,
		bsVertical = 3,
		bsFDiagonal = 4,
		bsBDiagonal = 5,
		bsCross = 6,
		bsDiagCross = 7
	}TxBrushStyle;
	enum
	{
		ipglsSolid = 0,
		ipglsDash = 1,
		ipglsDot = 2
	}TxiPlotGridLineStyle;
	enum
	{
		ipasText = 0,
		ipasLine = 1,
		ipasRectangle = 2,
		ipasLineX = 3,
		ipasLineY = 4,
		ipasImage = 5,
		ipasTextRectangle = 6,
		ipasEllipse = 7,
		ipasTextBox = 8
	}TxiPlotAnnotationStyle;
	enum
	{
		iprtDataView = 0,
		iprtChannel = 1,
		iprtXChannelYDataView = 2,
		iprtXDataViewYChannel = 3
	}TxiPlotReferenceType;
	enum
	{
		ipdrScale = 0,
		ipdrPercent = 1
	}TxiPlotDigitalReferenceStyle;
	enum
	{
		ipdpsValid = 0,
		ipdpsNull = 1,
		ipdpsEmpty = 2
	}TxiPlotDataPointStatus;
	enum
	{
		ipcsValueXY = 0,
		ipcsValueX = 1,
		ipcsValueY = 2,
		ipcsDeltaX = 3,
		ipcsDeltaY = 4,
		ipcsInverseDeltaX = 5
	}TxiPlotDataCursorStyle;
	enum
	{
		iosBottomRight = 0,
		iosTopLeft = 1
	}TxiOrientationSide;
	enum
	{
		iplsLineX = 0,
		iplsLineY = 1,
		iplsBandX = 2,
		iplsBandY = 3,
		iplsPolyBandX = 4,
		iplsPolyBandY = 5
	}TxiPlotLimitStyle;
	enum
	{
		ira000 = 0,
		ira090 = 1,
		ira180 = 2,
		ira270 = 3
	}TxiRotationAngle;
	enum
	{
		iahCenter = 0,
		iahLeft = 1,
		iahRight = 2
	}TxiAlignmentHorizontal;
	enum
	{
		ipistStraightLine = 0,
		ipistCubicSpline = 1,
		ipistPolynomial = 2,
		ipistRational = 3,
		ipistDifferential = 4,
		ipistDifferentialTerminated = 5
	}TxiPlotInterpolationStyle;
	enum
	{
		iopcxvsOPCServerTimeStamp = 0,
		iopcxvsSystemTimeStamp = 1,
		iopcxvsElapsedTime = 2,
		iopcxvsElapsedSeconds = 3
	}TxiOPCXValueSourceStyle;
	enum
	{
		ipfsModal = 0,
		ipfsStayOnTop = 1
	}TxiPlotFormStyle;
	enum
	{
		ipefMetaFile = 0,
		ipefBitmap = 1,
		ipefJPEG = 2
	}TxiPlotExportFormat;
	enum
	{
		ipcsNone = 0,
		ipcsMaster = 1,
		ipcsChild = 2
	}TxiPlotCartesianStyle;
	enum
	{
		ipdsStandard = 0,
		ipdsCompact = 1,
		ipdsCompactInterval = 2,
		ipdsFullFeature = 3
	}TxiPlotDataStyle;
	enum
	{
		iavCenter = 0,
		iavTop = 1,
		iavBottom = 2
	}TxiAlignmentVertical;
	enum
	{
		ifdTopBottom = 0,
		ifdBottomTop = 1,
		ifdLeftRight = 2,
		ifdRightLeft = 3,
		ifdTopLeftBottomRight = 4,
		ifdBottomRightTopLeft = 5,
		ifdBottomLeftTopRight = 6,
		ifdTopRightBottomLeft = 7,
		ifdRectangleOut = 8,
		ifdRectangleIn = 9,
		ifdCircleOut = 10,
		ifdCircleIn = 11
	}TxiFillDirection;
	enum
	{
		htKeyword = 0,
		htContext = 1
	}TxHelpType;
	enum
	{
		isccDC = 0,
		isccAC = 1,
		isccGround = 2
	}TxiScopeChannelCoupling;
	enum
	{
		ipttMajor = 0,
		ipttMinor = 1
	}TxiPlotTickType;
	enum
	{
		ipacsXAxis = 0,
		ipacsYAxis = 1,
		ipacsBoth = 2
	}TxiPlotAxesControlStyle;
	enum
	{
		ipfcsTab = 0,
		ipdfcsComma = 1
	}TxiPlotDataFileColumnSeparator;
	enum
	{
		iplcncsFont = 0,
		iplcncsChannelColor = 1,
		iplcncsXAxisFontColor = 2,
		iplcncsYAxisFontColor = 3
	}TxiPlotLegendChannelNameColorStyle;
	enum
	{
		ipdffText = 0,
		ipdffCompactInterval = 1
	}TxiPlotDataFileFormat;
	enum
	{
		iphlsOpenClose = 0,
		iphlsCandleStick = 1
	}TxiPlotHighLowStyle;
	enum
	{
		ipamScroll = 0,
		ipamZoom = 1
	}TxiPlotAxisMode;
	enum
	{
		iptbbtResume = 0,
		iptbbtPause = 1,
		iptbbtScrollAxesMode = 2,
		iptbbtZoomAxesMode = 3,
		iptbbtSelect = 4,
		iptbbtZoomBox = 5,
		iptbbtZoomOut = 6,
		iptbbtZoomIn = 7,
		iptbbtCursor = 8,
		iptbbtEdit = 9,
		iptbbtCopy = 10,
		iptbbtSave = 11,
		iptbbtPrint = 12,
		iptbbtPreview = 13
	}TxiPlotToolBarButtonType;
};
