// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CiPlotLimitX wrapper class

class CiPlotLimitX : public COleDispatchDriver
{
public:
	CiPlotLimitX() {}		// Calls COleDispatchDriver default constructor
	CiPlotLimitX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotLimitX(const CiPlotLimitX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	long GetLineStyle();
	void SetLineStyle(long nNewValue);
	long GetLineWidth();
	void SetLineWidth(long nNewValue);
	long GetFillStyle();
	void SetFillStyle(long nNewValue);
	CString GetXAxisName();
	void SetXAxisName(LPCTSTR lpszNewValue);
	CString GetYAxisName();
	void SetYAxisName(LPCTSTR lpszNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	double GetLine1Position();
	void SetLine1Position(double newValue);
	double GetLine2Position();
	void SetLine2Position(double newValue);
	void ClearAllElements();
	void AddBandElement(double Position, double UpperLimit, double LowerLimit);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetPopupEnabled();
	void SetPopupEnabled(BOOL bNewValue);
};
